name: React build
on:
    push: # master Branch에서 push 이벤트가 일어났을 때만 실행
        branches:
            - Kyun
            - dodie

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - names: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.BACK_HOST }}
                  username: ${{ secrets.BACK_USERNAME }}
                  password: ${{ secrets.BACK_PASSWORD }}
                  script: |
                      pm2 stop www
                      cd healthy-miok
                      cd backend 
                      sudo npm install
                      sudo npm start
